// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7W4kb6aEpaiGvUlxA28A3ACRe9kmQX1M',
    appId: '1:1036271212860:web:a6e5e569fa7d7998016639',
    messagingSenderId: '1036271212860',
    projectId: 'fir-learning-2e5c4',
    authDomain: 'fir-learning-2e5c4.firebaseapp.com',
    storageBucket: 'fir-learning-2e5c4.appspot.com',
    measurementId: 'G-TBYM0DVE1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpXW0cyTiGzaQkuPHHtATF0DGWbaEx00',
    appId: '1:1036271212860:android:ce041bbcfb58e3ce016639',
    messagingSenderId: '1036271212860',
    projectId: 'fir-learning-2e5c4',
    storageBucket: 'fir-learning-2e5c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpX_p0waimtjWGQs31aVUmyafkHrgM4BI',
    appId: '1:1036271212860:ios:da7b73bc040d4e3b016639',
    messagingSenderId: '1036271212860',
    projectId: 'fir-learning-2e5c4',
    storageBucket: 'fir-learning-2e5c4.appspot.com',
    iosClientId: '1036271212860-8kcfh57bppua5qo4rfr3vht2okagccq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselearning',
  );
}
